#! /bin/sh

sxhkd & 
nm-applet &
picom &
xrdb merge ~/.Xresources &
nitrogen --restore &
~/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6   

bspc config border_width        0 
bspc config window_gap       50 
bsp config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config top_padding 30

bspc config focused_border_color "#83a598"
bspc config normal_border_color "#2D2B55"
bspc config gapless_monocle false 
